CREATE TABLE `CATEGORIA` (`ID` INT NOT NULL AUTO_INCREMENT,
	`NOMBRE` VARCHAR(60),
    PRIMARY KEY (`ID`),
    UNIQUE KEY `ID` (`ID`)
    );
    
CREATE TABLE `PLATILLOS` (ID INT NOT NULL AUTO_INCREMENT,
	`NOMBRE` VARCHAR(50) DEFAULT NULL,
    `PRECIO` FLOAT DEFAULT NULL,
    `DISPONIBLE` TINYINT(1) DEFAULT NULL,
    `CATEGORIAID` INT(11) DEFAULT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY ID (`ID`),
    FOREIGN KEY (`CATEGORIAID`) REFERENCES `CATEGORIA` (`ID`)
	);
    
CREATE TABLE `RESERVACIONES` (ID INT NOT NULL AUTO_INCREMENT,
	`NOMBRE` VARCHAR(30) NOT NULL,
    `APELLIDO` VARCHAR(30) NOT NULL,
    `HORA` TIME DEFAULT NULL,
    `FECHA` DATE NOT NULL,
	PRIMARY KEY (`ID`),
    UNIQUE KEY `ID` (`ID`)
	);
    
INSERT INTO `CATEGORIA` (`NOMBRE`) VALUES ("ENTRADA"),("PLATO_PRINCIPAL"),("ENSALADAS"),("POSTRES"),("BEBIDAS"),("BEBIDAS_CON_ALCOHOL");


